export default function Head() {
  return (
    <>
      <title>KONPOL COMPANY</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      {/* <link
        rel="shortcut icon"
        type="image/png"
        href="../image/Konpol-logo.png"
      /> */}
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="/public/static/Konpol-logo.png" />
    </>
  );
}
